version: '2'
services:
  nginx:
    build: nginx/
    ports:
     - "5000:80"
    volumes:
     - /code/phpinfo:/var/www/html
     - /code/DockerDev/nginx/sites-available/:/etc/nginx/sites-enabled
    depends_on:
     - redis
     - db
     - elastic
    links:
        - redis
        - db
        - elastic
  redis:
    image: redis
  db:
    image: mysql
    ports: 
        - "3306:3306"
    environment:
        MYSQL_DATABASE: "mybase"
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_USER: "alan"
        MYSQL_PASSWORD: "abc789"
  elastic:
    build: elastic
    ports:
        - "9200:9200"
        - "9300:9300"
